### ISSUE TITLE
Better size selection for the widget (height, width)

### ISSUE THREAD

**Issue by christianbumann** [TUCRAIL/AdoPipelineOverview#53]
With other widgets (e.g. markdown widget) it is possible to select the width and hight separate.
This would make the widget more flexibel

**Comment by GABRIELNGBTUC** [comment]
Good idea. 

Unfortunately, Microsoft does not provide the source for this widget or guidance in the documentation on how to setup a widget with this way of configuring the size. So I'll have to look up on how to do this.

**Comment by christianbumann** [comment]
Ok I will try to fine example code. I didn't took a look on your changes for version 2.0.0.2 but there are less options now than with version 1.x.

 Is the current drop down filled by the microsoft sdk or by yourself?
It would be nice to have some more options  in the lower number e.g. 1x1, 1x2, 1x3, 2x1, 2x2, 2x3, 3x1, 3x2, 3x3.

**Comment by GABRIELNGBTUC** [comment]
The issue with the lower sizes is that the widget now looks like this in 2 x 1.

![image](https://github.com/user-attachments/assets/8924d4d8-79ae-4e1d-90ee-b44936fa7f91)

Or like this in 1 x 2

![image](https://github.com/user-attachments/assets/37f77055-8fd9-41f7-9bc1-03ab2078de26)

Adjusting CSS to support back these lower sizes could work (ie: overflow-y: scroll, max-width on the dropdowns, ...).

But for now, the simplest solution was to remove these broken sizes from the supported sizes

**Comment by christianbumann** [comment]
O perfect. Done with the latest widget release.
Many thanks
